name: docker-dotnet6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/sitecontagem-dotnet6-preview2
  CAMINHO_PROJETO_WEBAPP: ./SiteContagem

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Testes
      run: |
        service postgresql-x64-13 start
        ps -aux | more
